# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/AffPolySig',
                'doc_host': 'https://sarasvaluto.github.io',
                'git_url': 'https://github.com/sarasvaluto/AffPolySig',
                'lib_path': 'AffPolySig'},
  'syms': {'AffPolySig.core': {'AffPolySig.core.foo': ('core.html#foo', 'AffPolySig/core.py')}}}
